const fs = require('fs');

const commonContact = {
  address: 'Av. Gral. José de San Martín 2180 (Florencio Varela)',
  email: 'automotoresos-car@hotmail.com',
  phone: '4287-1431',
  phoneAlt: '4275-1489 / 4275-0302 - 4255-3571 / 5364-0401',
  cell: '15-6248-4394',
  whatsapp: '5491562484394'
};

const vehicles = [
  {
    id: 'honda-hrv-ex-cvt',
    name: 'Honda HR-V EX CVT',
    category: 'camionetas',
    condition: '0km',
    year: 2026,
    brand: 'Honda',
    price: 'Consultar Precio',
    priceNote: 'Financiación disponible con cuotas fijas en pesos',
    isFinanced: true,
    financeNote: 'Amplia financiación en cuotas fijas solo con DNI',
    image: 'assets/vehicles/honda-hrv.png',
    gallery: [
      'assets/vehicles/honda-hrv.png'
    ],
    km: '0 km',
    engine: '1.8 i-VTEC 140 CV',
    transmission: 'CVT Automática',
    fuel: 'Nafta',
    traction: 'Delantera',
    color: 'Gris Grafito Metalizado',
    moreInfo: 'AMPLIA FINANCIACIÓN CUOTAS FIJAS EN PESOS SOLO CON DNI - Podes ver nuestra gran variedad de vehiculos 0km y usados en www.automotoresoscar.com.ar . O también podes Comunicarte a nuestros tel. 4275-1489/ 4275-0302 - 4255-3571/5364-0401 facebook os-car automotores',
    equipamiento: {
      confort: [
        'Aire acondicionado',
        'Alarma de luces encendidas',
        'Apertura remota de baúl',
        'Asiento conductor regulable en altura',
        'Asiento trasero rebatible',
        'Cierre centralizado con mando a distancia',
        'Cierre centralizado de puertas',
        'Computadora de abordo',
        'Control de velocidad crucero',
        'Espejos exteriores eléctricos',
        'Faros regulables desde el interior',
        'Vidrios eléctricos delanteros',
        'Vidrios eléctricos delanteros y traseros',
        'Volante regulable',
        'Dirección Hidráulica'
      ],
      seguridad: [
        'Airbag acompañante',
        'Airbag conductor',
        'Airbag laterales',
        'Alarma',
        'Apoya cabeza en asientos traseros',
        'Cierre de puertas automático en movimiento',
        'Faros antiniebla delanteros',
        'Faros antiniebla traseros',
        'Frenos ABS',
        'Inmovilizador de motor',
        'Isofix',
        'Regulador de velocidad',
        'Repartidor electrónico de frenado',
        'Sensor de estacionamiento',
        'Tercer luz de stop'
      ],
      exterior: [
        'Barra porta equipaje',
        'Faros de xenón',
        'Limpia/lava luneta',
        'Llantas de aleación',
        'Paragolpes color carrocería'
      ],
      multimedia: [
        'Bluetooth',
        'Cargador de CD',
        'Comando satelital de stereo',
        'Entrada auxiliar',
        'Entrada USB',
        'GPS',
        'Manos libres',
        'Radio AM/FM',
        'Reproduce CD',
        'Reproduce MP3',
        'Tarjeta SD',
        'Volante multi-función'
      ]
    },
    features: [
      'Aire acondicionado y Climatizador',
      'Control de velocidad crucero',
      'Computadora de abordo',
      'Airbag conductor, acompañante y laterales',
      'Frenos ABS con repartidor de frenado',
      'Anclajes ISOFIX',
      'Sensores de estacionamiento',
      'Llantas de aleación y barras porta equipaje',
      'GPS, Bluetooth, USB, Tarjeta SD y manos libres',
      'Volante multifunción regulable'
    ],
    description: 'El SUV urbano de referencia de Honda en su versión EX con caja automática CVT. Confort supremo, diseño vanguardista, altísima seguridad con airbags laterales y anclajes ISOFIX, conectividad integral y amplio baúl para la familia.',
    contact: commonContact,
    sourceUrl: 'https://www.automotoresoscar.com.ar/camioneta-honda-hrv-0km-1584132390/31979'
  },
  {
    id: 'fiat-cronos-drive',
    name: 'Fiat Cronos Drive Pack Conec',
    category: 'autos',
    condition: '0km',
    year: 2026,
    brand: 'Fiat',
    price: 'Consultar Precio',
    priceNote: 'Financiación disponible con cuotas fijas en pesos',
    isFinanced: true,
    financeNote: 'Amplia financiación en cuotas fijas solo con DNI',
    image: 'assets/vehicles/fiat-cronos.png',
    gallery: [
      'assets/vehicles/fiat-cronos.png'
    ],
    km: '0 km',
    engine: '1.3 Firefly 99 CV',
    transmission: 'Manual 5 vel.',
    fuel: 'Nafta',
    traction: 'Delantera',
    color: 'Plata Bari Metalizado',
    moreInfo: 'AMPLIA FINANCIACION CUOTAS FIJAS EN PESOS SOLO CON DNI - Podes ver nuestra gran variedad de vehiculos 0km y usados en www.automotoresoscar.com.ar . O también podes Comunicarte a nuestros tel. 4275-1489/ 4275-0302 - 4255-3571/5364-0401 facebook os-car automotores',
    equipamiento: {
      confort: [
        'Aire acondicionado',
        'Alarma de luces encendidas',
        'Apertura remota de baúl',
        'Asiento conductor regulable en altura',
        'Asiento trasero rebatible',
        'Cierre centralizado con mando a distancia',
        'Cierre centralizado de puertas',
        'Climatizador automático',
        'Computadora de abordo',
        'Control de velocidad crucero',
        'Espejos exteriores eléctricos',
        'Faros regulables desde el interior',
        'Tapizado de cuero',
        'Vidrios eléctricos delanteros',
        'Vidrios eléctricos delanteros y traseros',
        'Volante regulable',
        'Dirección Hidráulica'
      ],
      seguridad: [
        'Airbag acompañante',
        'Airbag conductor',
        'Airbag laterales',
        'Alarma',
        'Apoya cabeza en asientos traseros',
        'Cierre de puertas automático en movimiento',
        'Control de estabilidad (ESP)',
        'Faros antiniebla delanteros',
        'Faros antiniebla traseros',
        'Frenos ABS',
        'Inmovilizador de motor',
        'Isofix',
        'Repartidor electrónico de frenado',
        'Tercer luz de stop'
      ],
      exterior: [
        'Llantas de aleación',
        'Paragolpes color carrocería'
      ],
      multimedia: [
        'Bluetooth',
        'Cargador de CD',
        'Comando satelital de stereo',
        'Entrada auxiliar',
        'Entrada USB',
        'Manos libres',
        'Radio AM/FM',
        'Reproduce CD',
        'Reproduce MP3',
        'Volante multi-función'
      ]
    },
    features: [
      'Climatizador automático',
      'Tapizado de cuero',
      'Control de estabilidad (ESP)',
      'Control de velocidad crucero',
      'Computadora de abordo',
      'Airbags conductor, acompañante y laterales',
      'Frenos ABS con repartidor de frenado',
      'Llantas de aleación',
      'Bluetooth con manos libres y comando satelital',
      'Cierre centralizado con mando a distancia'
    ],
    description: 'El sedán más vendido de Argentina en su configuración Drive Pack Conectividad. Equipado con tapizado de cuero, climatizador automático, control de estabilidad (ESP), y el motor 1.3 Firefly de bajísimo consumo y mantenimiento accesible.',
    contact: commonContact,
    sourceUrl: 'https://www.automotoresoscar.com.ar/auto-fiat-cronos-0km-1604345095/32195'
  },
  {
    id: 'peugeot-208-like',
    name: 'Peugeot 208 Like 1.2L',
    category: 'autos',
    condition: '0km',
    year: 2026,
    brand: 'Peugeot',
    price: 'Consultar Precio',
    priceNote: 'Financiación disponible con cuotas fijas en pesos',
    isFinanced: true,
    financeNote: 'Amplia financiación en cuotas fijas solo con DNI',
    image: 'assets/vehicles/peugeot-208.png',
    gallery: [
      'assets/vehicles/peugeot-208.png'
    ],
    km: '0 km',
    engine: '1.2 PureTech 82 CV',
    transmission: 'Manual 5 vel.',
    fuel: 'Nafta',
    traction: 'Delantera',
    color: 'Blanco Banquise',
    moreInfo: 'AMPLIA FINANCIACIÓN CUOTAS FIJAS EN PESOS SOLO CON DNI - Podes ver nuestra gran variedad de vehiculos 0km y usados en www.automotoresoscar.com.ar . O también podes Comunicarte a nuestros tel. 4275-1489/ 4275-0302 - 4255-3571 facebook os-car automotores',
    equipamiento: {
      confort: [
        'Aire acondicionado',
        'Alarma de luces encendidas',
        'Apertura remota de baúl',
        'Asiento trasero rebatible',
        'Cierre centralizado con mando a distancia',
        'Cierre centralizado de puertas',
        'Computadora de abordo',
        'Vidrios eléctricos delanteros',
        'Volante regulable',
        'Dirección Hidráulica'
      ],
      seguridad: [
        'Airbag acompañante',
        'Airbag conductor',
        'Apoya cabeza en asientos traseros',
        'Cierre de puertas automático en movimiento',
        'Frenos ABS',
        'Inmovilizador de motor',
        'Tercer luz de stop'
      ],
      exterior: [
        'Limpia/lava luneta',
        'Paragolpes color carrocería'
      ],
      multimedia: [
        'Bluetooth',
        'Comando satelital de stereo',
        'Entrada auxiliar',
        'Entrada USB',
        'Radio AM/FM'
      ]
    },
    features: [
      'Aire acondicionado',
      'Computadora de abordo',
      'Cierre centralizado con mando a distancia',
      'Vidrios eléctricos delanteros',
      'Doble airbag frontal',
      'Frenos ABS con asistencia',
      'Cierre de puertas automático en movimiento',
      'Conectividad Bluetooth, USB y Auxiliar',
      'Comando satelital de stereo'
    ],
    description: 'El hatchback del león que combina diseño europeo vanguardista, eficiencia sobresaliente y confort para la vida urbana. Líneas audaces, excelente posición de manejo y economía de combustible excepcional.',
    contact: commonContact,
    sourceUrl: 'https://www.automotoresoscar.com.ar/auto-peugeot-208-0km-1604604324/32203'
  },
  {
    id: 'toyota-sw4-4x4-2012',
    name: 'Toyota SW4 4x4 7 Asientos',
    category: 'camionetas',
    condition: 'usado',
    year: 2012,
    brand: 'Toyota',
    price: 'Consultar Precio',
    priceNote: 'Unidad seleccionada en excelente estado',
    isFinanced: true,
    financeNote: 'AMPLIA FINANCIACION CUOTAS FIJAS EN PESOS SOLO CON DNI',
    image: 'assets/vehicles/toyota-sw4.png',
    gallery: [
      'assets/vehicles/toyota-sw4.png'
    ],
    km: '248.000 km',
    engine: '3.0 D-4D Turbo Diesel 171 CV',
    transmission: 'Automática',
    fuel: 'Diesel',
    traction: '4x4 Doble Tracción',
    color: 'Negro Perlado',
    moreInfo: 'AMPLIA FINANCIACION CUOTAS FIJAS EN PESOS SOLO CON DNI - Podes ver nuestra gran variedad de vehiculos 0km y usados en www.automotoresoscar.com.ar . O también podes Comunicarte a nuestros tel. 4275-1489/ 4275-0302 - 4255-3571/5364-0401 facebook os-car automotores',
    equipamiento: {
      confort: [
        'Aire acondicionado',
        'Alarma de luces encendidas',
        'Apertura remota de baúl',
        'Asiento conductor regulable en altura',
        'Asiento trasero rebatible',
        'Asientos eléctricos',
        'Cierre centralizado con mando a distancia',
        'Cierre centralizado de puertas',
        'Climatizador automático',
        'Computadora de abordo',
        'Control de velocidad crucero',
        'Espejos exteriores eléctricos',
        'Faros regulables desde el interior',
        'Tapizado de cuero',
        'Techo corredizo',
        'Vidrios eléctricos delanteros',
        'Vidrios eléctricos delanteros y traseros',
        'Volante regulable',
        'Dirección Asistida',
        'Dirección Hidráulica'
      ],
      seguridad: [
        'Airbag acompañante',
        'Airbag conductor',
        'Airbag de cortina',
        'Airbag laterales',
        'Airbag trasero',
        'Alarma',
        'Apoya cabeza en asientos traseros',
        'Blindado',
        'Cierre de puertas automático en movimiento',
        'Control de estabilidad (ESP)',
        'Control de tracción',
        'Doble tracción',
        'Faros antiniebla delanteros',
        'Faros antiniebla traseros',
        'Frenos ABS',
        'Inmovilizador de motor',
        'Isofix',
        'Regulador de velocidad',
        'Repartidor electrónico de frenado',
        'Sensor de estacionamiento',
        'Sensor de lluvia',
        'Sensor de luz',
        'Tercer luz de stop'
      ],
      exterior: [
        'Barra porta equipaje',
        'Faros de xenón',
        'Limpia/lava luneta',
        'Llantas de aleación',
        'Paragolpes color carrocería',
        'Vidrios polarizados'
      ],
      multimedia: [
        'Bluetooth',
        'Cargador de CD',
        'Comando satelital de stereo',
        'Entrada auxiliar',
        'Entrada USB',
        'GPS',
        'Manos libres',
        'Pasacassette',
        'Radio AM/FM',
        'Reproduce CD',
        'Reproduce DVD',
        'Reproduce MP3',
        'Tarjeta SD',
        'Volante multi-función'
      ]
    },
    features: [
      'Capacidad para 7 pasajeros en 3 filas',
      'Doble tracción 4x4 con reductora',
      'Asientos eléctricos con tapizado de cuero',
      'Techo corredizo eléctrico',
      'Climatizador automático bizona',
      'Control de estabilidad (ESP) y control de tracción',
      'Airbags frontales, laterales, de cortina y traseros',
      'Blindado y vidrios polarizados',
      'Sensores de estacionamiento, lluvia y luz',
      'Faros de xenón y barras porta equipaje',
      'Pantalla multimedia con GPS, DVD, Bluetooth y SD'
    ],
    description: 'La SUV todoterreno más codiciada y respetada de Argentina. Versión 7 asientos con tracción 4x4, tapizado de cuero, asientos eléctricos, techo corredizo, sistema blindado y máximo nivel de equipamiento de seguridad y confort.',
    contact: commonContact
  },
  {
    id: 'chevrolet-onix-premier-turbo',
    name: 'Chevrolet Onix Premier 1.0 Turbo A/T',
    category: 'autos',
    condition: '0km',
    year: 2026,
    brand: 'Chevrolet',
    price: 'Consultar Precio',
    priceNote: 'Financiación disponible con cuotas fijas en pesos',
    isFinanced: true,
    financeNote: 'Amplia financiación en cuotas fijas solo con DNI',
    image: 'assets/vehicles/chevrolet-onix.png',
    gallery: [
      'assets/vehicles/chevrolet-onix.png'
    ],
    km: '0 km',
    engine: '1.0 Turbo Ecotec 116 CV',
    transmission: 'Automática 6 vel.',
    fuel: 'Nafta',
    traction: 'Delantera',
    color: 'Plata Switchblade',
    moreInfo: 'AMPLIA FINANCIACIÓN CUOTAS FIJAS EN PESOS SOLO CON DNI - Podes ver nuestra gran variedad de vehiculos 0km y usados en www.automotoresoscar.com.ar . O también podes Comunicarte a nuestros tel. 4275-1489/ 4275-0302 - 4255-3571/5364-0401 facebook os-car automotores',
    equipamiento: {
      confort: [
        'Aire acondicionado',
        'Alarma de luces encendidas',
        'Apertura remota de baúl',
        'Asiento conductor regulable en altura',
        'Asiento trasero rebatible',
        'Asientos eléctricos',
        'Cierre centralizado con mando a distancia',
        'Cierre centralizado de puertas',
        'Climatizador automático',
        'Computadora de abordo',
        'Control de velocidad crucero',
        'Espejos exteriores eléctricos',
        'Faros regulables desde el interior',
        'Tapizado de cuero',
        'Techo corredizo',
        'Vidrios eléctricos delanteros',
        'Vidrios eléctricos delanteros y traseros',
        'Volante regulable',
        'Dirección Hidráulica'
      ],
      seguridad: [
        'Airbag acompañante',
        'Airbag conductor',
        'Airbag de cortina',
        'Airbag laterales',
        'Airbag trasero',
        'Alarma',
        'Apoya cabeza en asientos traseros',
        'Cierre de puertas automático en movimiento',
        'Control de estabilidad (ESP)',
        'Faros antiniebla delanteros',
        'Faros antiniebla traseros',
        'Frenos ABS',
        'Inmovilizador de motor',
        'Isofix',
        'Regulador de velocidad',
        'Repartidor electrónico de frenado',
        'Sensor de estacionamiento',
        'Sensor de luz',
        'Tercer luz de stop'
      ],
      exterior: [
        'Limpia/lava luneta',
        'Llantas de aleación',
        'Paragolpes color carrocería'
      ],
      multimedia: [
        'Bluetooth',
        'Cargador de CD',
        'Comando satelital de stereo',
        'Entrada auxiliar',
        'Entrada USB',
        'GPS',
        'Manos libres',
        'Radio AM/FM',
        'Reproduce DVD',
        'Volante multi-función'
      ]
    },
    features: [
      'Motor 1.0 Turbo 116 CV con caja automática de 6 marchas',
      'Tapizado de cuero bitono y techo corredizo',
      'Climatizador automático digital',
      'Control de estabilidad (ESP) y regulador de velocidad',
      '6 Airbags (frontales, laterales y de cortina)',
      'Frenos ABS con repartidor de frenado y anclajes ISOFIX',
      'Sensores de estacionamiento y encendido automático de luces',
      'Pantalla multimedia con GPS, DVD, Bluetooth y USB',
      'Llantas de aleación diamantadas'
    ],
    description: 'La versión tope de gama Premier del nuevo Chevrolet Onix. Combina el eficiente motor 1.0 Turbo con transmisión automática de 6 velocidades, habitáculo en cuero con techo solar, máxima puntuación en seguridad (6 airbags + ESP) y conectividad avanzada.',
    contact: commonContact,
    sourceUrl: 'https://www.automotoresoscar.com.ar/auto-chevrolet-onix-0km-1611357440/32276'
  },
  {
    id: 'renault-alaskan-confort',
    name: 'Renault Alaskan Confort 4x2',
    category: 'camionetas',
    condition: '0km',
    year: 2026,
    brand: 'Renault',
    price: 'Consultar Precio',
    priceNote: 'Financiación disponible con cuotas fijas en pesos',
    isFinanced: true,
    financeNote: 'Amplia financiación en cuotas fijas solo con DNI',
    image: 'assets/vehicles/renault-alaskan.png',
    gallery: [
      'assets/vehicles/renault-alaskan.png'
    ],
    km: '0 km',
    engine: '2.3 dCi Turbo Diesel 160 CV',
    transmission: 'Manual 6 vel.',
    fuel: 'Diesel',
    traction: '4x2 Trasera',
    color: 'Plata Metalizado',
    moreInfo: 'AMPLIA FINANCIACION CUOTAS FIJAS EN PESOS SOLO CON DNI - Podes ver nuestra gran variedad de vehiculos 0km y usados en www.automotoresoscar.com.ar . O también podes Comunicarte a nuestros tel. 4275-1489/ 4275-0302 - 4255-3571/5364-0401 facebook os-car automotores',
    equipamiento: {
      confort: [
        'Aire acondicionado',
        'Alarma de luces encendidas',
        'Apertura remota de baúl',
        'Asiento conductor regulable en altura',
        'Asiento trasero rebatible',
        'Cierre centralizado con mando a distancia',
        'Cierre centralizado de puertas',
        'Computadora de abordo',
        'Control de velocidad crucero',
        'Espejos exteriores eléctricos',
        'Faros regulables desde el interior',
        'Vidrios eléctricos delanteros',
        'Vidrios eléctricos delanteros y traseros',
        'Volante regulable',
        'Dirección Hidráulica'
      ],
      seguridad: [
        'Airbag acompañante',
        'Airbag conductor',
        'Alarma',
        'Faros antiniebla delanteros',
        'Faros antiniebla traseros',
        'Frenos ABS',
        'Inmovilizador de motor',
        'Isofix',
        'Tercer luz de stop'
      ],
      exterior: [
        'Paragolpes color carrocería'
      ],
      multimedia: [
        'Bluetooth',
        'Cargador de CD',
        'Comando satelital de stereo',
        'Entrada auxiliar',
        'Entrada USB',
        'Manos libres',
        'Radio AM/FM',
        'Reproduce MP3',
        'Volante multi-función'
      ]
    },
    features: [
      'Motor 2.3 dCi Turbo Diesel 160 CV con gran torque de trabajo',
      'Capacidad de carga superior a 1 tonelada',
      'Control de velocidad crucero',
      'Doble airbag frontal y frenos ABS con anclajes ISOFIX',
      'Cierre centralizado con mando a distancia y vidrios en las 4 puertas',
      'Conectividad Bluetooth, USB, Auxiliar y comando satelital de audio'
    ],
    description: 'La pick-up mediana de trabajo de Renault. Fuerte, confiable y con excelente capacidad de carga útil. Ideal tanto para labores intensivas de campo o industria como para el uso particular diario.',
    contact: commonContact,
    sourceUrl: 'https://www.automotoresoscar.com.ar/camioneta-renault-alaskan-0km-1615402897/32537'
  },
  {
    id: 'peugeot-2008-allure',
    name: 'Peugeot 2008 Allure 1.6L',
    category: 'camionetas',
    condition: '0km',
    year: 2026,
    brand: 'Peugeot',
    price: 'Consultar Precio',
    priceNote: 'Financiación disponible con cuotas fijas en pesos',
    isFinanced: true,
    financeNote: 'Amplia financiación en cuotas fijas solo con DNI',
    image: 'assets/vehicles/peugeot-2008.png',
    gallery: [
      'assets/vehicles/peugeot-2008.png'
    ],
    km: '0 km',
    engine: '1.6 VTi 115 CV',
    transmission: 'Manual 5 vel.',
    fuel: 'Nafta',
    traction: 'Delantera',
    color: 'Blanco Banquise',
    moreInfo: 'AMPLIA FINANCIACIÓN CUOTAS FIJAS EN PESOS SOLO CON DNI - Podes ver nuestra gran variedad de vehiculos 0km y usados en www.automotoresoscar.com.ar . O también podes Comunicarte a nuestros tel. 4275-1489/ 4275-0302 - 4255-3571/5364-0401 facebook os-car automotores',
    equipamiento: {
      confort: [
        'Aire acondicionado',
        'Alarma de luces encendidas',
        'Apertura remota de baúl',
        'Asiento conductor regulable en altura',
        'Asiento trasero rebatible',
        'Cierre centralizado con mando a distancia',
        'Cierre centralizado de puertas',
        'Computadora de abordo',
        'Control de velocidad crucero',
        'Espejos exteriores eléctricos',
        'Faros regulables desde el interior',
        'Vidrios eléctricos delanteros',
        'Vidrios eléctricos delanteros y traseros',
        'Volante regulable',
        'Dirección Hidráulica'
      ],
      seguridad: [
        'Airbag acompañante',
        'Airbag conductor',
        'Alarma',
        'Apoya cabeza en asientos traseros',
        'Cierre de puertas automático en movimiento',
        'Control de estabilidad (ESP)',
        'Faros antiniebla delanteros',
        'Faros antiniebla traseros',
        'Frenos ABS',
        'Inmovilizador de motor',
        'Isofix',
        'Regulador de velocidad',
        'Repartidor electrónico de frenado',
        'Sensor de estacionamiento',
        'Tercer luz de stop'
      ],
      exterior: [
        'Barra porta equipaje',
        'Limpia/lava luneta',
        'Paragolpes color carrocería'
      ],
      multimedia: [
        'Bluetooth',
        'Cargador de CD',
        'Comando satelital de stereo',
        'Entrada auxiliar',
        'Entrada USB',
        'Manos libres',
        'Radio AM/FM',
        'Volante multi-función'
      ]
    },
    features: [
      'Control de estabilidad (ESP) y sensor de estacionamiento',
      'Control de velocidad crucero con regulador de velocidad',
      'Airbags frontales y frenos ABS con repartidor electrónico (REF)',
      'Barras porta equipaje en el techo y faros antiniebla delanteros y traseros',
      'Conectividad Bluetooth, USB, manos libres y volante multifunción'
    ],
    description: 'El crossover compacto urbano de Peugeot en versión Allure. Diseño dinámico con barras de techo, despeje del suelo ideal para la ciudad o viajes familiares, conectividad completa y elevado equipamiento de seguridad.',
    contact: commonContact
  },
  {
    id: 'citroen-c4-lounge-life',
    name: 'Citroën C4 Lounge Life 1.6L',
    category: 'autos',
    condition: '0km',
    year: 2026,
    brand: 'Citroën',
    price: 'Consultar Precio',
    priceNote: 'Financiación disponible con cuotas fijas en pesos',
    isFinanced: true,
    financeNote: 'Amplia financiación en cuotas fijas solo con DNI',
    image: 'assets/vehicles/citroen-c4.png',
    gallery: [
      'assets/vehicles/citroen-c4.png'
    ],
    km: '0 km',
    engine: '1.6 VTi 115 CV',
    transmission: 'Manual 5 vel.',
    fuel: 'Nafta',
    traction: 'Delantera',
    color: 'Plata Metalizado',
    moreInfo: 'AMPLIA FINANCIACION CUOTAS FIJAS EN PESOS SOLO CON DNI - Podes ver nuestra gran variedad de vehiculos 0km y usados en www.automotoresoscar.com.ar . O también podes Comunicarte a nuestros tel. 4275-1489/ 4275-0302 - 4255-3571/5364-0401 facebook os-car automotores',
    equipamiento: {
      confort: [
        'Aire acondicionado',
        'Alarma de luces encendidas',
        'Apertura remota de baúl',
        'Asiento conductor regulable en altura',
        'Asiento trasero rebatible',
        'Cierre centralizado con mando a distancia',
        'Cierre centralizado de puertas',
        'Computadora de abordo',
        'Control de velocidad crucero',
        'Espejos exteriores eléctricos',
        'Faros regulables desde el interior',
        'Tapizado de cuero',
        'Vidrios eléctricos delanteros',
        'Vidrios eléctricos delanteros y traseros',
        'Volante regulable',
        'Dirección Hidráulica'
      ],
      seguridad: [
        'Airbag acompañante',
        'Airbag conductor',
        'Airbag laterales',
        'Alarma',
        'Apoya cabeza en asientos traseros',
        'Cierre de puertas automático en movimiento',
        'Control de estabilidad (ESP)',
        'Faros antiniebla delanteros',
        'Faros antiniebla traseros',
        'Frenos ABS',
        'Inmovilizador de motor',
        'Isofix',
        'Tercer luz de stop'
      ],
      exterior: [
        'Llantas de aleación',
        'Paragolpes color carrocería'
      ],
      multimedia: [
        'Bluetooth',
        'Cargador de CD',
        'Comando satelital de stereo',
        'Entrada auxiliar',
        'Entrada USB',
        'Manos libres',
        'Radio AM/FM',
        'Reproduce CD',
        'Volante multi-función'
      ]
    },
    features: [
      'Tapizado de cuero exclusivo',
      'Control de estabilidad (ESP)',
      'Airbags frontales y laterales',
      'Llantas de aleación',
      'Control de velocidad crucero y computadora de abordo',
      'Bluetooth, USB, manos libres y volante multifunción'
    ],
    description: 'El sedán familiar por excelencia de Citroën con tapizado de cuero, gran insonorización de habitáculo, el confort de marcha característico de la marca y financiación accesible solo con DNI.',
    contact: commonContact
  }
];

const header = '/**\n * Automotores Os-Car - Catálogo de Vehículos Oficial\n * Datos reales extraídos de automotoresoscar.com.ar con ficha técnica completa\n * Florencio Varela, Buenos Aires - Actualizado 2026\n */\n\n';
const output = header + 'const VEHICLES_DATA = ' + JSON.stringify(vehicles, null, 2) + ';\n';

fs.writeFileSync('js/vehicles-data.js', output, {encoding: 'utf8'});
console.log('Vehicles data generated successfully: ' + vehicles.length + ' vehicles.');
